version: "3"

services:
  postgres:
    container_name: oneToOneRelations
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=vitor
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=oneToOne
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
